"""Interpreter module responsible for executing the parsed Abstract Syntax Tree."""

from typing import Dict, Any, List
from .exceptions import VertexRuntimeError
from .lexer import Token
from .parser import (
    Parser, ASTNode, NumberNode, IdentifierNode, ListNode, IndexNode, BinOpNode,
    AssignNode, ListAssignNode, PrintNode, IfNode, WhileNode, ForNode, BlockNode
)

class Environment:
    """Stores variables and their current states during code execution."""
    
    def __init__(self) -> None:
        """Initialize an empty environment dictionary."""
        self.variables: Dict[str, Any] = {}

    def set(self, name: str, value: Any) -> None:
        """Set a variable's value in the environment."""
        self.variables[name] = value

    def get(self, name: str) -> Any:
        """Retrieve a variable's value from the environment.
        
        Raises:
            VertexRuntimeError: If the variable is not defined.
        """
        if name in self.variables:
            return self.variables[name]
        raise VertexRuntimeError(f"Undefined variable '{name}'")

class Interpreter:
    """Executes the AST generated by the Parser."""
    
    def __init__(self, env: Environment, output_widget: Any) -> None:
        """Initialize the Interpreter with an environment and a UI output widget."""
        self.env: Environment = env
        self.output_widget: Any = output_widget

    def execute(self, tokens: List[Token]) -> None:
        """Parse tokens and evaluate the resulting AST.
        
        Args:
            tokens (List[Token]): Lexical tokens to be executed.
        """
        parser = Parser(tokens)
        ast = parser.parse()
        self.evaluate(ast)

    def evaluate(self, node: ASTNode) -> Any:
        """Recursively evaluate an AST node and return its computed value.
        
        Args:
            node (ASTNode): The tree node to evaluate.
            
        Returns:
            Any: The evaluated result, depending on the node type.
        """
        if isinstance(node, NumberNode):
            return node.value
        elif isinstance(node, IdentifierNode):
            return self.env.get(node.name)
        elif isinstance(node, ListNode):
            return [self.evaluate(el) for el in node.elements]
        elif isinstance(node, IndexNode):
            lst = self.evaluate(node.left)
            idx = self.evaluate(node.index)
            if not isinstance(lst, list) or not isinstance(idx, int):
                raise VertexRuntimeError("Invalid index access")
            try:
                return lst[idx]
            except IndexError:
                raise VertexRuntimeError("Index out of bounds")
        elif isinstance(node, BinOpNode):
            left_val = self.evaluate(node.left)
            right_val = self.evaluate(node.right)
            op = node.op
            if op == "+": return left_val + right_val
            elif op == "-": return left_val - right_val
            elif op == "*": return left_val * right_val
            elif op == "/":
                if right_val == 0:
                    raise VertexRuntimeError("Division by zero!")
                return left_val // right_val
            elif op == "==": return 1 if left_val == right_val else 0
            elif op == "!=": return 1 if left_val != right_val else 0
            elif op == "<": return 1 if left_val < right_val else 0
            elif op == ">": return 1 if left_val > right_val else 0
            elif op == "<=": return 1 if left_val <= right_val else 0
            elif op == ">=": return 1 if left_val >= right_val else 0
        elif isinstance(node, AssignNode):
            val = self.evaluate(node.value)
            self.env.set(node.name, val)
            return val
        elif isinstance(node, ListAssignNode):
            lst = self.evaluate(node.left.left)
            idx = self.evaluate(node.left.index)
            val = self.evaluate(node.value)
            if not isinstance(lst, list) or not isinstance(idx, int):
                raise VertexRuntimeError("Invalid index assignment")
            try:
                lst[idx] = val
            except IndexError:
                raise VertexRuntimeError("Index out of bounds")
            return val
        elif isinstance(node, PrintNode):
            val = self.evaluate(node.expression)
            self.output_widget.insert("end", f"> {val}\n")
            return None
        elif isinstance(node, IfNode):
            cond = self.evaluate(node.condition)
            if cond:
                self.evaluate(node.then_branch)
            elif node.else_branch:
                self.evaluate(node.else_branch)
            return None
        elif isinstance(node, WhileNode):
            while self.evaluate(node.condition):
                self.evaluate(node.body)
            return None
        elif isinstance(node, ForNode):
            if node.init:
                self.evaluate(node.init)
            while node.condition is None or self.evaluate(node.condition):
                self.evaluate(node.body)
                if node.update:
                    self.evaluate(node.update)
            return None
        elif isinstance(node, BlockNode):
            for stmt in node.statements:
                self.evaluate(stmt)
            return None
        raise VertexRuntimeError("Unknown AST node type")